config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'm_weather' => 'm_weather#index'
  post 'url_reduce_url' => 'url#reduce_url'
  match 'url' => 'url#index', via: [:get, :post]
  # get 'u/:id' => "shortener/shortened_urls#show"
  get 'u/:id' => "url#temp_redirect"
  
  get 'lunch' => 'lunch#index'
  get 'lunch/list' => 'lunch#list'
  get 'lunch/newstore/:name' => 'lunch#newstore'
  get 'lunch/newform/:name' => 'lunch#newform'
  post 'lunch/updateform' => 'lunch#updateform'
  get 'lunch/form/:id' => 'lunch#form'
  post 'lunch/updatecommodity' => 'lunch#updatecommodity'
  get 'lunch/manage' => 'lunch#manage'
  get 'lunch/manage_store' => 'lunch#manage_store'
  get 'lunch/remove' => 'lunch#remove'
  get 'lunch/remove_store' => 'lunch#remove_store'
  get 'lunch/:id' => 'lunch#show'

  # get 'share_money/newuser' => 'share_money_account#newuser'
  get 'share_money/signup' => 'share_money_account#signup'
  post 'share_money/createuser' => 'share_money_account#createuser'
  get 'share_money/newaccount' => 'share_money_account#newaccount'
  post 'share_money/createaccount' => 'share_money_account#createaccount'
  post 'share_money/createrel/:rid' => 'share_money_account#createrel'
  get 'share_money/account/:rid' => 'share_money_account#account'
  post 'share_money/createitem/:rid' => 'share_money_account#createitem'
  delete 'share_money/destroyitem/:id' => 'share_money_account#destroyitem'
  delete 'share_money/destroyitem' => 'share_money_account#destroyitem'
  get 'share_money' => 'share_money_account#index'
  get 'share_money/login' => 'share_money_account#login'
  post 'share_money/login' => 'share_money_account#dologin'
  get 'share_money/logout' => 'share_money_account#logout'
  # get 'share_money/:uid' => 'share_money_account#index'

  get 'tmpstrmsg' => 'tmpstrmsg#index'
  match 'tmpstrmsg/add' => 'tmpstrmsg#add', via: [:get, :post]

  namespace :share_book do
    get '' => 'home#index'
    post 'login' => 'home#login'
    post 'reset' => 'home#reset'
    get 'create_book' => 'home#create_book'
    resources :book, only: [:show, :update] do
      member do
        get 'members', 'logout'
        post 'create_item', 'create_member', 'create_exchange'
        patch 'update_item', 'update_member', 'update_exchange'
        delete 'delete_item', 'delete_exchange'
      end
    end
  end

  get 'test/get' => 'test_api#get'
  post 'test/post' => 'test_api#post'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/share_book.rb
module ShareBook
  def self.table_name_prefix
    'share_book_'
  end
end

app/models/share_book/book.rb
class ShareBook::Book < ApplicationRecord
  has_many :members, -> { order(id: :asc) }, :class_name => "ShareBook::Member", :foreign_key => "book_id", :dependent => :destroy
  has_many :items, -> { order(time: :desc, id: :desc) }, :class_name => "ShareBook::Item", :foreign_key => "book_id", :dependent => :destroy
  has_many :exchanges, :class_name => "ShareBook::Exchange", :foreign_key => "book_id", :dependent => :destroy

  after_create :gen_token

  def gen_token
    loop do
      token = SecureRandom.hex(5)
      unless ShareBook::Book.exists?(token: token)
        self.token = token
        self.save
        return
      end
    end
  end

  def sum_price
    self.items.sum(:price)
  end

  def balance
    self.members.sum(&:sum_price)-self.sum_price
  end

end

app/models/share_book/exchange.rb
class ShareBook::Exchange < ApplicationRecord
  belongs_to :book, :class_name => "ShareBook::Book", :foreign_key => "book_id"

end

app/models/share_book/flow.rb
class ShareBook::Flow < ApplicationRecord
  belongs_to :member, :class_name => "ShareBook::Member", :foreign_key => "member_id"
  belongs_to :flow, :class_name => "ShareBook::Flow", :foreign_key => "flow_id"

  before_save :init_num

  def init_num
    self.number = 0 if self.number.nil?
  end

end

app/models/share_book/item.rb
class ShareBook::Item < ApplicationRecord
  belongs_to :book, :class_name => 'ShareBook::Book', :foreign_key => 'book_id'
  has_many :flows, :class_name => 'ShareBook::Flow', :foreign_key => 'item_id', :dependent => :destroy
  belongs_to :exchange, :class_name => 'ShareBook::Exchange', :foreign_key => 'exchange_id'

  accepts_nested_attributes_for :flows, :allow_destroy => true

  before_save :init_price

  def init_price
    self.price = 0 if self.price.nil?
    self.flows = self.flows.reject{|flow| flow.number == 0}
  end

  def time_str
    self.time.strftime("%m/%d %H:%M")
  end

  def member_flow member
    self.flows.find_by(:member_id => member.id)
  end

  def member_flow_num member
    member_flow(member)&.number || 0
  end

  def exchange_name
    self.exchange.currency
  end

end

app/models/share_book/member.rb
class ShareBook::Member < ApplicationRecord
  belongs_to :book, :class_name => "ShareBook::Book", :foreign_key => "book_id"
  has_many :flows, :class_name => "ShareBook::Flow", :foreign_key => "member_id", :dependent => :destroy

  after_create :gen_key

  def gen_key
    loop do
      key = SecureRandom.hex(5)
      unless ShareBook::Member.exists?(key: key)
        self.key = key
        self.save
        return
      end
    end
  end

  def self.validate token, key
    member = self.where(key: key).first
    return member if member.present? && member.book.token == token
    return nil
  end

  def sum_price
    self.flows.sum(&:number)
  end

end

app/controllers/share_book/book_controller.rb
class ShareBook::BookController < ShareBookController
  before_action { redirect_to share_book_path unless has_permission? }
  before_action :setup

  def show
  end

  def update
    @book.update(book_params)
  end

  def create_item
    params[:share_book_item][:price] = params[:share_book_item][:price].to_i * [-1, 1][params[:share_book_item][:sign].to_i]
    params[:share_book_item][:flows_attributes].each do |index, flow|
      flow[:number] = flow[:number].to_i * [-1, 1][flow[:sign].to_i]
    end
    # render json: params
    # return
    @book.items.create(item_params)

    redirect_to share_book_book_path
  end

  def members
  end

  def create_member
    @book.members.create(member_params)

    redirect_to members_share_book_book_path
  end

  def update_member
    @current_member.update(member_params)
    respond_to do |format|
      format.js
    end
  end

  def delete_item
    item = @book.items.find(params[:item_id])
    item.destroy

    redirect_to share_book_book_path
  end

  def create_exchange
    @book.exchanges.create(exchange_params)

    redirect_to members_share_book_book_path
  end

  def update_exchange
    exchange = @book.exchanges.find(params[:edit_id])
    exchange.update(exchange_params)
    respond_to do |format|
      format.js
    end
  end
  
  def logout
    clear_member
    redirect_to share_book_path
  end

private
  def setup
    @current_member = current_member
    @book = @current_member.book
  end

  def book_params
    params.require(:share_book_book).permit(:name)
  end

  def member_params
    params.require(:share_book_member).permit(:nick_name)
  end

  def item_params
    params.require(:share_book_item).permit(:title, :price, :time, flows_attributes: [:member_id, :number])
  end

  def exchange_params
    params.require(:share_book_exchange).permit(:currency, :value)
  end

end

app/controllers/share_book/home_controller.rb
class ShareBook::HomeController < ShareBookController
  layout "share_book"

  def index
    @old_member = old_member
  end

  def login
    member = set_member params[:token], params[:key]
    if member.present?
      redirect_to share_book_book_path(member)
    else
      @msg = 'Book not found'
      respond_to do |format|
        format.js
      end
    end
  end

  def reset
    reset_history
    redirect_to share_book_path
  end

  def create_book
    book = ShareBook::Book.create(
      name: 'new book',
      currency_name: 'TWD',
    )
    member = book.members.create(
      nick_name: 'new member',
    )

    set_member book.token, member.key

    redirect_to share_book_book_path(member.id)
  end

end

app/controllers/share_book/member_controller.rb
class ShareBook::MemberController < ShareBookController
end

app/controllers/share_book_controller.rb
class ShareBookController < ApplicationController

  def set_member token, key
    session[:token] = token
    session[:key] = key
    session[:o_token] = token
    session[:o_key] = key
    member = current_member
    unless member.present?
      clear_member
    end
    return member
  end

  def current_member
    return ShareBook::Member.validate(session[:token], session[:key])
  end

  def old_member
    return ShareBook::Member.validate(session[:o_token], session[:o_key])
  end

  def clear_member
    session[:token] = nil
    session[:key] = nil
  end

  def reset_history
    session[:o_token] = nil
    session[:o_key] = nil
  end

  def has_permission?
    current_member.present?
  end

end

app/helpers/share_book/book_helper.rb
module ShareBook::BookHelper
  def tri_selector arr, num
    return arr[num <=> 0]
  end

  def bound_str num, reverse = false
    return tri_selector ['', 'out-bound', 'in-bound'], num*(reverse ? 1:-1)
  end
end

app/helpers/share_book/home_helper.rb
module ShareBook::HomeHelper
end

app/helpers/share_book/member_helper.rb
module ShareBook::MemberHelper
end

app/views/share_book/book/_create_block.html.erb
<div class='create-block'>
  <div class='create-content'>
    <% new_item = @book.items.new %>
    <%= form_for new_item, url: create_item_share_book_book_path do |f| %>
      <div class='item'>
        <%= label_tag :title, '項目：' %>
        <%= f.text_field :title, required: true %>
      </div>

      <div class='item item-price'>
        <%= label_tag :price, '金額：' %>
        <%= f.number_field :price %>
        <% switcher_tag = "switcher-book-#{@book.id}" %>
        <div class="switcher book-switcher">
          <%= f.check_box :sign, id: switcher_tag, checked:true %>
          <label for="<%=switcher_tag%>"></label>
        </div>
      </div>

      <div class='item full'>
        <%= label_tag :time, '時間' %>
        <%= f.date_select :time, { :default => DateTime.now }, {class: 'item-date'} %>
        <%= f.time_select :time, { :default => Time.now }, {class: 'item-date'} %>
        <span class='hint btn'>重置時間</span>
      </div>

      <hr>

      <div class='member'>
        <% @book.members.each do |member|%>
          <%= f.fields_for :flows, new_item.flows.build, multiple: true do |flow_field| %>
            <%= render partial: 'range_block', locals: { f: flow_field, member: member } %>
          <% end %>
        <% end %>
      </div>

      <div class='action'>
        <span id='btn-create-close' class='btn'>取消</span>
        <%= submit_tag '新增', class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/share_book/book/_range_block.html.erb
<div class='range-block'>
  <% switcher_tag = "switcher-#{member.id}" %>
  <div class="switcher">
    <%= f.check_box :sign, id: switcher_tag, checked:true %>
    <label for="<%=switcher_tag%>"></label>
  </div>
  <%= f.hidden_field :member_id, value: member.id %>
  <%= f.number_field :number, class: 'flow' %>
  <%= f.label :name, "#{member.nick_name}", class: "member-nickname-#{member.id}" %>
</div>

app/views/share_book/book/members.html.erb
<div class='book setting'>
  <%= link_to "回帳本", share_book_book_path, class:'btn' %>

  <hr>

  <div class='setting-block'>
    <table>
      <tr>
        <th>
        </th>
        <th>
          成員名稱
        </th>
        <th>
          結餘
        </th>
      </tr>
      <% average = (@book.sum_price.to_f / @book.members.size).round(2) %>
      <% @book.members.each_with_index do |member, index| %>
        <tr class='member'>
          <td>
            <%= "->" if member.id == @current_member.id %>
          </td>
          <td>
            <%= "#{index+1}: #{member.nick_name}" %>
          </td>
          <td align='right'>
            <% diff = average-member.sum_price %>
            <span><%= ['','需補繳','可退款'][diff <=> 0] %><%= diff.abs.round(2) %></span>
          </td>
        </tr>
      <% end %>
    </table>

    <hr>

    <%= form_for ShareBook::Member.new, url: create_member_share_book_book_path do |f| %>
      <%= f.label :add_member, "新增成員：" %>
      <%= f.text_field :nick_name, required: true, class: 'input' %>
      <%= f.submit "新增", class: 'btn' %>
    <% end %>

    <hr>
  </div>
  <div class='setting-block'>
    <table>
      <caption>
        <%= label :currency, "貨幣" %>
      </caption>
      <tr>
        <td>
          <%= @book.currency_name %>
        </td>
        <td>
          1
        </td>
      </tr>
      <% @book.exchanges.each do |curr| %>
        <tr>
          <td>
            <%= curr.currency %>
          </td>
          <td>
            <%= render partial: 'common/editable', 
                locals: { t_label: '', t_url: update_exchange_share_book_book_path, t_content: curr.value, t_item: curr, t_attr: :value, t_id: curr.id } %>
          </td>
        </tr>
      <% end %>
    </table>

    <hr>

    <%= form_for ShareBook::Exchange.new, url: create_exchange_share_book_book_path do |f| %>
      <%= f.label :add_exchange, "新增幣別：" %> <br>
      <%= f.text_field :currency, placeholder: '幣別', required: true, class: 'input' %> <br>
      <%= f.number_field :value, placeholder: '匯率', step: '0.001', required: true, class: 'input' %> <br>
      <%= f.submit "新增", class: 'btn' %>
    <% end %>

    <hr>
  </div>

</div>

app/views/share_book/book/show.html.erb
<div class='book'>
  <div class='menu-icon'>
    <div class="bar1"></div>
    <div class="bar2"></div>
    <div class="bar3"></div>
  </div>
  <div class='menu'>
    <div>
      <%= label_tag :token, "Token: " %>
      <span><%= @book.token %></span>
    </div>
    <div>
      <%= label_tag :key, "Key: " %>
      <span><%= @current_member.key %></span>
    </div>

    <div class='action'>
      <%= link_to '設定', members_share_book_book_path, class:'btn fit' %>
      <%= link_to '登出', logout_share_book_book_path, class:'btn fit' %>
    </div>
    
  </div>

  <div class='content'>
    <div class='info wrapper'>
      <div class='info-item'>
        <%= render partial: 'common/editable', 
            locals: { t_label: '帳本名稱：', t_content: @book.name, t_item: @book, t_attr: :name } %>
      </div>

      <div class='info-item'>
        <%= render partial: 'common/editable', 
            locals: { t_label: '成員名稱：', t_url: update_member_share_book_book_path, t_content: @current_member.nick_name, t_item: @current_member, t_attr: :nick_name } %>
      </div>
    </div>

    <div class='info wrapper'>
      <div class='info-item'>
        <%= label :item, '帳本結餘：' %>    
        <span class='<%= bound_str @book.balance, true %>'><%= ['','盈餘','虧損'][@book.balance <=> 0] %><%= @book.balance.abs %></span>
      </div>
      <div class='info-item'>
        <%= label :item, '帳本支出：' %>   
        <span class='in-bound'>■</span>
        &nbsp;
        <%= label :item, '帳本收入：' %>   
        <span class='out-bound'>■</span>
      </div>
    </div>

    <div class='info wrapper'>
      <div class='info-item'>
        <%= label :currency, '主要幣別：' %>   
        <span><%= @book.currency_name %></span>        
      </div>
    </div>

    <hr>

    <div class='item-table wrapper'>
      <div class='item-table-row'>
        <span class='time'><%= label :item, '時間' %></span>
        <span class='title'><%= label :item, '品項' %></span>
        <span class='price money'><%= label :item, '價格' %></span>
        <% @book.members.each do |member| %>
          <span class='member-nickname-<%=member.id%> money'><%= member.nick_name %></span>
        <% end %>
        <span class='del'><%= label :item, '' %></span>
      </div>
      <% @book.items.each do |item| %>
        <div class='item-table-row'>
          <span><%= item.time_str %></span>
          <span><%= item.title %></span>
          <span class='money <%= bound_str item.price %>'>
            <%= tri_selector(['','支','收'], item.price) %>&nbsp;<%= item.price.abs %>
            <%= "(#{item.exchange_name})" if item.exchange_id.present? %>
          </span>
          <% @book.members.each do |member| %>
            <% flow_num = item.member_flow_num(member) %>
            <span class='money <%= bound_str flow_num, true %>'>
              <%= flow_num.abs %>
            </span>
          <% end %>
          <span class='del'><%= link_to '╳', delete_item_share_book_book_path(item_id: item.id), class: 'btn-del', :method => :delete %></span>
        </div>
      <% end %>
      <div class='item-table-row'>
        <span>總計</span>
        <span></span>
        <span class='money <%= bound_str @book.sum_price %>'>
          <%= tri_selector(['','支','收'], @book.sum_price) %>&nbsp;<%= @book.sum_price.abs %>
        </span>
        <% @book.members.each do |member| %>
          <span class='money <%= bound_str member.sum_price, true %>'><%= member.sum_price.abs %></span>
        <% end %>
        <span></span>
      </div>
      <br>
      <div class='item-table-row end-row'>
        <span>分帳</span>
        <span></span>
        <span></span>
        <% average = (@book.sum_price.to_f / @book.members.size).round(2) %>
        <% @book.members.each do |member| %>
          <% diff = average-member.sum_price %>
          <span class='money <%= bound_str diff %>'>
            <%= ['','需補繳','可退款'][diff <=> 0] %><%= diff.abs.round(2) %>
          </span>
        <% end %>
      </div>
    </div>

    <hr>

    <%= render partial: 'create_block' %>

    <span id='btn-create-popup' class='btn'>新增項目</span>
    
  </div>
</div>

app/views/share_book/book/update_member.js.erb
$('.member-nickname-<%=@current_member.id%>').text('<%=@current_member.nick_name%>');